version: 0.2
env:
  variables:
    DIST_FOLDER: "dist"
    BUILD_ENV: "dev"
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Install dependencies"
      - cd datalake
      - npm install
  build:
    commands:
      - echo "Doing a SAM translation on sample.yaml"
      - echo "The package command will put the Lambda function code into S3"
      - echo "It will then create a new version of the template file with the S3 url to the source code"
      - echo "Learn more at https://docs.aws.amazon.com/lambda/latest/dg/serverless_app.html"
      - pwd
      - npm test
