version: 0.2
env:
  variables:
    DIST_FOLDER: "dist"
    BUILD_ENV: "dev"
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Install dependencies"
      - cd datalake/code
      - npm install
      - npm test
  build:
    commands:
      - ls -a
      - pwd
      - cd ../..
      - ls -a
      - LAST_COMMIT=$(git rev-parse HEAD~1)
      - minusversion=$(git diff "$LAST_COMMIT" ./package.json | grep -c '\-\s*\"version\"*')
      - plusversion=$(git diff "$LAST_COMMIT" ./package.json | grep -c '\+\s*\"version\"*') 
      - echo "minus version $minusversion"
      - echo "plusversion $plusversion"

      
