version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Install dependencies"
      - cd datalake/code
      - npm install
  build:
    commands:
      - echo "Running npm test"
      - npm test
