version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Install dependencies"
      - ls -a
      - cd datalake/code
      - npm install
  build:
    commands:
      - echo "Running npm test"
      - npm test
      - pwd
      - ls -a
      - LAST_COMMIT=$(git rev-parse HEAD~1)
      - git branch
      - git fetch --all
      - git remote prune origin
      - git branch
      - git log
      - git diff "$LAST_COMMIT" ./package.json
      - minusversion=$(git diff "$LAST_COMMIT" ./package.json | grep -c '\-\s*\"version\"*')
      - plusversion=$(git diff "$LAST_COMMIT" ./package.json | grep -c '\+\s*\"version\"*') 
      - | 
        if [[ ( "$minusversion" == 1 ) && ( "$plusversion" == 1 ) ]];
        then
            echo "npm publish"
            aws codeartifact login --tool npm --domain data-lake --domain-owner 293952095306 --repository data-lake-delivery-module
            npm publish; else
            echo "Not a new version";
        fi
