name: Watch release branches

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:

  deploy:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::293952095306:role/account-deployer
          role-duration-seconds: 7200
      - name: AWS CodePipeline Trigger
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        if: contains(github.ref, 'release')
        with:
          aws-region: "ap-southeast-2"
          pipeline-name: "deploypipeline-test"