name: Trigger codepipeline SNS

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - release/*

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
     # - name: Configure AWS Credentials
     #   uses: aws-actions/configure-aws-credentials@v1
     #   with:
     #     aws-access-key-id: ${{ secrets.ACCESS_AWS_ACCESS_KEY_ID }}
     #     aws-secret-access-key: ${{ secrets.ACCESS_AWS_SECRET_ACCESS_KEY }}
     #     aws-region: ap-southeast-2
     #     role-to-assume: arn:aws:iam::293952095306:role/account-deployer
     #     role-duration-seconds: 7200
      - name: Publish SNS Topic
        uses: nothingalike/sns-publish-topic@v1.6
        with:
          MESSAGE: "Repo: ${{ github.repository }} attempted to build ref |${{ github.ref }}| into base_Ref ${{ github.base_ref }}"
          TOPIC_ARN: "arn:aws:sns:ap-southeast-2:293952095306:Setup-Pipeline-PipelineSNSTopic-1K4LMEJHA4FB"
        env:
          AWS_REGION: ap-southeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_AWS_SECRET_ACCESS_KEY }}